import Link from "next/link";

export const metadata = {
    title: 'Next || Contact Us',
    description: 'Generated by Next.js',
}
const Contact = () => {
    return (
        <div>
            This is Contact Page

            <Link href='/'>
                <button className="btn btn-active btn-warning mt-8">go to home</button>
            </Link>
        </div>
    );
};

export default Contact;